# Verify that dependencies resolve
install:
  stage: test
  image: python
  script:
    - pip3 install -r requirements.txt
    - pip3 install -r requirements_test.txt
    - python3 -m pytest tests/test_init.py

# PyPI template
.pypi:
  stage: deploy
  image: python
  before_script:
    # Install build and distribution tools
    - python3 -m pip install --user --upgrade setuptools wheel
    # Build the package
    - python3 setup.py sdist bdist_wheel
    # Prepare to upload to PyPI
    - python3 -m pip install --user --upgrade twine
  artifacts:
    paths:
      - dist/
      
# Upload dev builds to TestPyPI
testpypi:
  extends: .pypi
  only:
    - dev@klikini/doorbirdpy
  script:
    # Upload to TestPyPI
    - python3 -m twine upload --repository-url https://test.pypi.org/legacy/ -u __token__ dist/*

# Upload master builds to PyPI
realpypi:
  extends: .pypi
  only:
    - master@klikini/doorbirdpy
  script:
    # Upload to PyPI
    - python3 -m twine upload -u __token__ dist/*
